# Generated by Django 4.1.5 on 2023-02-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="books",
            field=models.ManyToManyField(related_name="books", to="books.book"),
        ),
    ]
